/**
 * Accounting & Payments Module Use Cases
 */

export const accountingUseCases = [
  // Payment Collection Use Cases
  {
    id: "acct-payment-full",
    module: "accounting",
    category: "payment",
    title: "Full Payment at Order (Credit Card)",
    complexity: "basic",
    description: "Customer pays full amount via credit card at time of order",
    testSteps: [
      "Create Sales Order",
      "Process credit card payment",
      "Verify payment captured",
      "Mark order as paid",
      "Generate receipt",
      "Release order for fulfillment",
    ],
    expectedOutcome:
      "Payment received, order released for immediate fulfillment",
    productsNeeded: 1,
  },
  {
    id: "acct-payment-cash",
    module: "accounting",
    category: "payment",
    title: "Cash Payment at Pickup/Delivery",
    complexity: "basic",
    description: "Customer pays cash when order is picked up or delivered",
    testSteps: [
      "Create COD (Cash on Delivery) order",
      "Process and ship order",
      "Collect cash at delivery",
      "Record payment in system",
      "Generate cash receipt",
      "Close order",
    ],
    expectedOutcome: "Cash collected and recorded, order marked as paid",
    productsNeeded: 1,
  },
  {
    id: "acct-payment-partial",
    module: "accounting",
    category: "payment",
    title: "Partial Payment Received",
    complexity: "medium",
    description: "Customer makes partial payment against invoice",
    testSteps: [
      "Invoice for $1,000 generated",
      "Customer pays $600",
      "Record partial payment",
      "System tracks $400 balance",
      "Age the remaining balance",
      "Follow up for remainder",
    ],
    expectedOutcome: "Partial payment applied, outstanding balance tracked",
    productsNeeded: 1,
  },
  {
    id: "acct-payment-check",
    module: "accounting",
    category: "payment",
    title: "Payment via Check - Pending Clearance",
    complexity: "medium",
    description: "Customer pays by check which requires clearance period",
    testSteps: [
      "Receive check payment",
      "Record check with pending status",
      "Deposit check to bank",
      "Wait for clearance (3-5 days)",
      "Update status to cleared",
      "Release order if held",
    ],
    expectedOutcome: "Check tracked through clearance process",
    productsNeeded: 1,
  },
  {
    id: "acct-payment-multiple",
    module: "accounting",
    category: "payment",
    title: "Multiple Payment Methods",
    complexity: "complex",
    description: "Single order paid with multiple payment methods",
    testSteps: [
      "Order total: $500",
      "Customer pays $200 gift card",
      "Customer pays $300 credit card",
      "Record both payments",
      "Link to single order",
      "Generate split receipt",
    ],
    expectedOutcome: "Multiple payments properly allocated to single order",
    productsNeeded: 1,
  },
  {
    id: "acct-payment-fifo",
    module: "accounting",
    category: "payment",
    title: "Payment Applied to Oldest Invoice (FIFO)",
    complexity: "complex",
    description:
      "Payment automatically applied to oldest outstanding invoices first",
    testSteps: [
      "Customer has 3 open invoices",
      "Invoice 1: $200 (60 days old)",
      "Invoice 2: $300 (30 days old)",
      "Invoice 3: $250 (current)",
      "Customer pays $400",
      "System applies $200 to Invoice 1, $200 to Invoice 2",
      "Invoice 2 shows $100 balance",
    ],
    expectedOutcome: "Payment waterfall applied oldest-first",
    productsNeeded: 1,
  },

  // Prepayment Use Cases
  {
    id: "acct-prepay-full",
    module: "accounting",
    category: "prepayment",
    title: "Full Prepayment Required",
    complexity: "basic",
    description: "Order cannot process until full payment received",
    testSteps: [
      "Create order for new customer",
      "System requires prepayment",
      "Order held until payment",
      "Customer submits payment",
      "Payment verified",
      "Order released for processing",
    ],
    expectedOutcome: "Order held until prepayment received and verified",
    productsNeeded: 1,
  },
  {
    id: "acct-prepay-deposit",
    module: "accounting",
    category: "prepayment",
    title: "Deposit Required (% of Order)",
    complexity: "medium",
    description: "Customer must pay percentage deposit before processing",
    testSteps: [
      "Order total: $1,000",
      "Deposit required: 50% ($500)",
      "Customer pays deposit",
      "Order processing begins",
      "Balance due on delivery",
      "Collect remaining $500",
    ],
    expectedOutcome:
      "Deposit collected, balance tracked and collected at delivery",
    productsNeeded: 1,
  },
  {
    id: "acct-prepay-balance-due",
    module: "accounting",
    category: "prepayment",
    title: "Prepayment with Balance Due on Delivery",
    complexity: "medium",
    description: "Partial prepayment with remainder due at delivery",
    testSteps: [
      "Collect prepayment amount",
      "Process and ship order",
      "System tracks balance due",
      "Collect balance at delivery",
      "Record final payment",
      "Close order",
    ],
    expectedOutcome: "Split payment tracked across order lifecycle",
    productsNeeded: 1,
  },
  {
    id: "acct-prepay-account",
    module: "accounting",
    category: "prepayment",
    title: "Prepaid Customer Account - Deduct Balance",
    complexity: "complex",
    description: "Customer has prepaid account balance to draw from",
    testSteps: [
      "Customer has $2,000 account credit",
      "Place order for $350",
      "Deduct from prepaid balance",
      "New balance: $1,650",
      "No payment collection needed",
      "Track balance for future orders",
    ],
    expectedOutcome: "Order paid from prepaid balance, account updated",
    productsNeeded: 1,
  },
  {
    id: "acct-prepay-refund",
    module: "accounting",
    category: "prepayment",
    title: "Prepayment Refund (Order Cancelled)",
    complexity: "complex",
    description: "Customer cancels order after prepayment made",
    testSteps: [
      "Customer prepays $500",
      "Customer cancels order",
      "Calculate refund amount",
      "Process refund to original payment method",
      "Or: Apply as account credit",
      "Close cancelled order",
    ],
    expectedOutcome: "Prepayment refunded or converted to account credit",
    productsNeeded: 1,
  },

  // Net Terms / Credit Use Cases
  {
    id: "acct-net30",
    module: "accounting",
    category: "net-terms",
    title: "Net 30 Terms",
    complexity: "basic",
    description: "Standard 30-day payment terms",
    testSteps: [
      "Ship order to credit customer",
      "Generate invoice dated today",
      "Due date = 30 days from invoice",
      "Track in AR aging",
      "Collect payment within terms",
      "Close invoice",
    ],
    expectedOutcome: "Invoice generated, tracked, and collected within 30 days",
    productsNeeded: 1,
  },
  {
    id: "acct-net60",
    module: "accounting",
    category: "net-terms",
    title: "Net 60 Terms - Extended Payment",
    complexity: "medium",
    description: "Extended 60-day payment terms for key accounts",
    testSteps: [
      "Verify customer approved for Net 60",
      "Process and ship order",
      "Generate invoice with 60-day terms",
      "Track extended aging",
      "Send payment reminder at 45 days",
      "Collect by due date",
    ],
    expectedOutcome: "Extended terms properly tracked and collected",
    productsNeeded: 1,
  },
  {
    id: "acct-early-discount",
    module: "accounting",
    category: "net-terms",
    title: "2/10 Net 30 - Early Payment Discount",
    complexity: "medium",
    description: "Offer 2% discount if paid within 10 days",
    testSteps: [
      "Invoice for $1,000, terms 2/10 Net 30",
      "Customer pays within 10 days",
      "Calculate 2% discount: $20",
      "Accept payment of $980",
      "Record discount taken",
      "Close invoice",
    ],
    expectedOutcome: "Early payment discount applied correctly",
    productsNeeded: 1,
  },
  {
    id: "acct-credit-limit-hold",
    module: "accounting",
    category: "net-terms",
    title: "Credit Limit Check - Order on Hold",
    complexity: "complex",
    description: "Order exceeds customer credit limit",
    testSteps: [
      "Customer credit limit: $5,000",
      "Current AR balance: $4,200",
      "New order: $1,500",
      "System blocks order (would exceed limit)",
      "Notify credit manager",
      "Either collect payment or approve exception",
      "Release order",
    ],
    expectedOutcome: "Order held for credit review, released after resolution",
    productsNeeded: 1,
  },
  {
    id: "acct-past-due-block",
    module: "accounting",
    category: "net-terms",
    title: "Past Due Account - Block New Orders",
    complexity: "complex",
    description: "Customer has past due invoices, new orders blocked",
    testSteps: [
      "Customer has 60-day past due invoice",
      "System flags account as delinquent",
      "New order attempted",
      "System blocks new orders",
      "Require payment of past due balance",
      "Once paid, release account for new orders",
    ],
    expectedOutcome: "Account blocked until past due resolved",
    productsNeeded: 1,
  },
  {
    id: "acct-credit-increase",
    module: "accounting",
    category: "net-terms",
    title: "Credit Limit Increase Request",
    complexity: "complex",
    description: "Process request to increase customer credit limit",
    testSteps: [
      "Customer requests credit increase",
      "Review payment history",
      "Check credit references",
      "Evaluate risk",
      "Approve or deny request",
      "Update customer credit limit",
      "Notify customer of decision",
    ],
    expectedOutcome: "Credit limit reviewed and updated based on analysis",
    productsNeeded: 0,
  },

  // Invoice & AR Use Cases
  {
    id: "acct-invoice-generate",
    module: "accounting",
    category: "invoice",
    title: "Generate Invoice from Delivery",
    complexity: "basic",
    description: "Create invoice when goods are shipped",
    testSteps: [
      "Complete delivery note",
      "System generates invoice",
      "Verify invoice details",
      "Send invoice to customer",
      "Track in AR",
    ],
    expectedOutcome: "Invoice created and sent automatically on delivery",
    productsNeeded: 1,
  },
  {
    id: "acct-invoice-consolidated",
    module: "accounting",
    category: "invoice",
    title: "Consolidated Invoice (Multiple Deliveries)",
    complexity: "medium",
    description: "Single invoice for multiple shipments",
    testSteps: [
      "Customer receives 5 shipments in a week",
      "End of week: generate consolidated invoice",
      "All deliveries on one invoice",
      "Send single invoice to customer",
      "Track as single AR item",
    ],
    expectedOutcome: "Multiple deliveries billed on single invoice",
    productsNeeded: 3,
  },
  {
    id: "acct-invoice-proforma",
    module: "accounting",
    category: "invoice",
    title: "Proforma Invoice Before Shipment",
    complexity: "medium",
    description:
      "Generate proforma invoice for customer approval before shipping",
    testSteps: [
      "Create order",
      "Generate proforma invoice",
      "Send to customer for approval",
      "Customer approves/pays",
      "Convert to actual invoice",
      "Ship order",
    ],
    expectedOutcome: "Proforma approved before commitment to ship",
    productsNeeded: 1,
  },
  {
    id: "acct-invoice-partial",
    module: "accounting",
    category: "invoice",
    title: "Partial Invoice - Shipped Items Only",
    complexity: "complex",
    description: "Invoice only for items actually shipped",
    testSteps: [
      "Order for 100 units",
      "Ship 60 units (40 backordered)",
      "Invoice for 60 units only",
      "When backorder ships, invoice remainder",
      "Customer receives two invoices",
      "Track both in AR",
    ],
    expectedOutcome: "Invoicing matches actual shipments",
    productsNeeded: 1,
  },
  {
    id: "acct-credit-memo",
    module: "accounting",
    category: "invoice",
    title: "Credit Memo / Adjustment",
    complexity: "complex",
    description:
      "Issue credit memo for returns, pricing errors, or adjustments",
    testSteps: [
      "Customer returns 10 units",
      "Create credit memo for returned value",
      "Link to original invoice",
      "Apply credit to customer account",
      "Customer can use credit on future orders",
      "Or: Issue refund",
    ],
    expectedOutcome: "Credit memo issued and applied to account",
    productsNeeded: 1,
  },
  {
    id: "acct-aging-collections",
    module: "accounting",
    category: "invoice",
    title: "Aging Report and Collections Workflow",
    complexity: "complex",
    description: "Work aged receivables through collection process",
    testSteps: [
      "Run AR aging report",
      "Identify invoices 30/60/90+ days past due",
      "Generate collection letters/calls",
      "Document collection activity",
      "Escalate if needed",
      "Write off uncollectible or send to collections",
    ],
    expectedOutcome: "Systematic collection of aged receivables",
    productsNeeded: 0,
  },

  // Accounts Receivable Use Cases
  {
    id: "acct-ar-short-paid",
    module: "accounting",
    category: "ar",
    title: "Short Paid Invoice",
    complexity: "medium",
    description: "Customer pays less than the invoice amount",
    testSteps: [
      "Invoice generated for $1,000",
      "Customer sends payment of $850",
      "Record payment against invoice",
      "System calculates $150 short pay",
      "Research reason for short payment",
      "Create adjustment or follow up for balance",
      "Document short pay resolution",
    ],
    expectedOutcome: "Short payment recorded, balance tracked for follow-up",
    productsNeeded: 1,
  },
  {
    id: "acct-ar-overpaid",
    module: "accounting",
    category: "ar",
    title: "Invoice Over Paid - Credit Created",
    complexity: "medium",
    description: "Customer overpays invoice, credit memo issued",
    testSteps: [
      "Invoice generated for $500",
      "Customer sends payment of $600",
      "Record overpayment of $100",
      "Create credit memo for $100",
      "Apply credit to customer account",
      "Notify customer of credit balance",
      "Credit available for future invoices",
    ],
    expectedOutcome: "Overpayment captured as credit memo on customer account",
    productsNeeded: 1,
  },
  {
    id: "acct-ar-return-after-payment",
    module: "accounting",
    category: "ar",
    title: "Product Returned After Payment Received",
    complexity: "complex",
    description: "Customer returns product after invoice was already paid",
    testSteps: [
      "Invoice for $750 generated and paid",
      "Customer returns product (full or partial)",
      "Create return authorization",
      "Receive returned goods",
      "Generate credit memo for return value",
      "Process refund to customer",
      "Or: Apply credit to future invoice",
    ],
    expectedOutcome: "Return processed with refund or credit issued for paid invoice",
    productsNeeded: 1,
  },
  {
    id: "acct-ar-return-before-payment",
    module: "accounting",
    category: "ar",
    title: "Product Returned Before Payment Received",
    complexity: "medium",
    description: "Customer returns product while invoice is still open/unpaid",
    testSteps: [
      "Invoice for $500 generated but unpaid",
      "Customer initiates return",
      "Create return authorization",
      "Receive returned goods",
      "Generate credit memo",
      "Apply credit to open invoice",
      "Adjust invoice balance accordingly",
      "Collect reduced balance if any",
    ],
    expectedOutcome: "Credit applied to open invoice, balance reduced",
    productsNeeded: 1,
  },
];

export const accountingCategories = [
  {
    id: "payment",
    name: "Payment Collection",
    description: "Receiving customer payments",
  },
  {
    id: "prepayment",
    name: "Prepayment",
    description: "Advance payment workflows",
  },
  {
    id: "net-terms",
    name: "Net Terms / Credit",
    description: "Credit terms and limits",
  },
  {
    id: "invoice",
    name: "Invoice & AR",
    description: "Invoicing and receivables",
  },
  {
    id: "ar",
    name: "Accounts Receivable",
    description: "AR adjustments, short pays, overpayments, and returns",
  },
];
