/**
 * Expired & Damaged Inventory Module Use Cases
 */

export const expiredDamagedUseCases = [
  // Expired Items Use Cases
  {
    id: "exp-pull-single",
    module: "expired-damaged",
    category: "expired",
    title: "Pull Expired Item from Shelf",
    complexity: "basic",
    description: "Identify and remove single expired item during routine check",
    testSteps: [
      "Perform shelf check or cycle count",
      "Identify expired product",
      "Scan GS1 barcode to confirm expiry",
      "Remove from sellable location",
      "Move to expired hold area",
      "Create inventory adjustment",
      "Schedule for disposal",
    ],
    expectedOutcome: "Expired item removed from sellable inventory",
    productsNeeded: 1,
  },
  {
    id: "exp-batch-report",
    module: "expired-damaged",
    category: "expired",
    title: "Batch Expiry Report - Pull Multiple Items",
    complexity: "medium",
    description: "Run expiry report and pull all expired products",
    testSteps: [
      "Generate expiry report (all expired)",
      "Print pull list",
      "Navigate to each location",
      "Scan and remove each expired item",
      "Consolidate in expired hold area",
      "Create batch inventory adjustment",
      "Document total write-off value",
    ],
    expectedOutcome: "All expired products identified and removed",
    productsNeeded: 3,
  },
  {
    id: "exp-near-expiry-clearance",
    module: "expired-damaged",
    category: "expired",
    title: "Near-Expiry Alert - Move to Clearance",
    complexity: "medium",
    description: "Move soon-to-expire products to clearance area",
    testSteps: [
      "Run report: expiring in next 30 days",
      "Generate move list",
      "Pick items from regular locations",
      "Move to clearance/discount area",
      "Update location in system",
      "Flag for clearance pricing",
      "Monitor for sale before expiry",
    ],
    expectedOutcome: "Near-expiry items moved to clearance for quick sale",
    productsNeeded: 2,
    flags: ["near-expiry"],
  },
  {
    id: "exp-during-pick-substitute",
    module: "expired-damaged",
    category: "expired",
    title: "Expired Found During Pick - Substitute",
    complexity: "complex",
    description: "Discover expired item while picking customer order",
    testSteps: [
      "Begin picking order",
      "Scan product - system shows expired",
      "Cannot fulfill with expired product",
      "Check for alternate lot",
      "If available: pick alternate lot",
      "If not: partial pick or backorder",
      "Remove expired from location",
      "Report expired item",
    ],
    expectedOutcome: "Order fulfilled from valid lot, expired item quarantined",
    productsNeeded: 1,
    flags: ["substitution"],
  },
  {
    id: "exp-disposal-documentation",
    module: "expired-damaged",
    category: "expired",
    title: "Disposal with Chain of Custody",
    complexity: "complex",
    description: "Formally dispose expired products with documentation",
    testSteps: [
      "Consolidate expired items for disposal",
      "Document each item (lot, qty, value)",
      "Two-person witness for destruction",
      "Complete disposal method (shred, landfill, etc.)",
      "Both parties sign disposal record",
      "File documentation",
      "Complete inventory write-off",
    ],
    expectedOutcome: "Expired products disposed with proper documentation",
    productsNeeded: 2,
    flags: ["disposal", "chain-of-custody"],
  },

  // Damaged Items Use Cases
  {
    id: "dmg-during-pick",
    module: "expired-damaged",
    category: "damaged",
    title: "Damage Discovered During Picking",
    complexity: "basic",
    description: "Find damaged product while picking order",
    testSteps: [
      "Begin picking order",
      "Observe damage on product",
      "Cannot ship damaged item",
      "Set aside damaged product",
      "Pick from alternate stock",
      "Complete order",
      "Report damaged item",
      "Move to damaged hold area",
    ],
    expectedOutcome: "Order fulfilled from good stock, damage reported",
    productsNeeded: 1,
  },
  {
    id: "dmg-cycle-count",
    module: "expired-damaged",
    category: "damaged",
    title: "Damage Found During Cycle Count",
    complexity: "medium",
    description: "Discover damaged inventory during count",
    testSteps: [
      "Perform cycle count",
      "Find damaged units",
      "Document damage type and quantity",
      "Adjust count for damaged items",
      "Move damaged to hold area",
      "Create damage report",
      "Investigate cause",
    ],
    expectedOutcome: "Inventory adjusted, damage documented and investigated",
    productsNeeded: 1,
  },
  {
    id: "dmg-partial-repack",
    module: "expired-damaged",
    category: "damaged",
    title: "Partial Damage - Repack Remaining",
    complexity: "medium",
    description: "Some units in case damaged, salvage good units",
    testSteps: [
      "Case of 24 units",
      "4 units damaged",
      "Remove damaged units",
      "Inspect remaining 20 units",
      "20 units good condition",
      "Repack or move to open stock",
      "Adjust case inventory",
      "Write off 4 damaged",
    ],
    expectedOutcome: "Good units salvaged, damaged units written off",
    productsNeeded: 1,
  },
  {
    id: "dmg-insurance-claim",
    module: "expired-damaged",
    category: "damaged",
    title: "Insurance Claim Documentation",
    complexity: "complex",
    description: "Document damage for insurance claim",
    testSteps: [
      "Significant damage event occurs",
      "Secure and document damage scene",
      "Photograph all damage",
      "Complete inventory of damaged items",
      "Calculate replacement value",
      "File insurance claim",
      "Provide supporting documentation",
      "Track claim to resolution",
    ],
    expectedOutcome: "Insurance claim filed with proper documentation",
    productsNeeded: 3,
    flags: ["insurance"],
  },
  {
    id: "dmg-root-cause",
    module: "expired-damaged",
    category: "damaged",
    title: "Root Cause Analysis",
    complexity: "complex",
    description: "Investigate recurring damage at location",
    testSteps: [
      "Multiple damage reports from same area",
      "Review damage patterns",
      "Inspect location/equipment",
      "Interview staff",
      "Identify root cause",
      "Implement corrective action",
      "Monitor for improvement",
      "Document findings",
    ],
    expectedOutcome: "Root cause identified and corrected",
    productsNeeded: 0,
    flags: ["investigation"],
  },

  // Disposition Workflow Use Cases
  {
    id: "disp-destroy",
    module: "expired-damaged",
    category: "disposition",
    title: "Disposition: Destroy/Scrap",
    complexity: "medium",
    description: "Product cannot be salvaged, must be destroyed",
    testSteps: [
      "Review item for disposition",
      "Determine unsalvageable",
      "Select disposition: Destroy",
      "Document reason",
      "Complete destruction process",
      "Witness signs off",
      "Write off inventory value",
    ],
    expectedOutcome: "Product destroyed with documentation",
    productsNeeded: 1,
  },
  {
    id: "disp-return-vendor",
    module: "expired-damaged",
    category: "disposition",
    title: "Disposition: Return to Vendor",
    complexity: "medium",
    description: "Defective product returned to vendor for credit",
    testSteps: [
      "Review item for disposition",
      "Vendor accepts returns",
      "Create vendor RMA",
      "Pack and ship to vendor",
      "Track shipment",
      "Await vendor credit",
      "Apply credit to AP",
    ],
    expectedOutcome: "Product returned to vendor, credit received",
    productsNeeded: 1,
  },
  {
    id: "disp-discount-sell",
    module: "expired-damaged",
    category: "disposition",
    title: "Disposition: Discount and Sell",
    complexity: "medium",
    description: "Cosmetically damaged but functional, sell at discount",
    testSteps: [
      "Review item condition",
      "Functional but cosmetic damage",
      "Calculate discount (e.g., 50% off)",
      "Move to clearance area",
      "Update pricing",
      'List as "open box" or "scratch & dent"',
      "Track sale",
    ],
    expectedOutcome: "Product sold at discount, value recovered",
    productsNeeded: 1,
  },
  {
    id: "disp-repack-relabel",
    module: "expired-damaged",
    category: "disposition",
    title: "Disposition: Repack/Relabel",
    complexity: "complex",
    description: "Product good but packaging damaged",
    testSteps: [
      "Inspect product condition",
      "Product good, packaging damaged",
      "Obtain new packaging",
      "Repack product",
      "Apply new labels",
      "Return to sellable inventory",
      "Document repack activity",
    ],
    expectedOutcome: "Product repackaged and returned to inventory",
    productsNeeded: 1,
  },
  {
    id: "disp-workflow-complete",
    module: "expired-damaged",
    category: "disposition",
    title: "Complete Disposition Workflow",
    complexity: "complex",
    description: "Full end-to-end disposition process",
    testSteps: [
      "1. Identify issue (scan GS1)",
      "2. Document condition (photo/notes)",
      "3. Select disposition type",
      "4. Route to appropriate area",
      "5. Execute disposition action",
      "6. Update inventory status",
      "7. Generate required documentation",
      "8. Close disposition record",
    ],
    expectedOutcome: "Complete disposition with full audit trail",
    productsNeeded: 1,
  },
];

export const expiredDamagedCategories = [
  {
    id: "expired",
    name: "Expired Items",
    description: "Handling expired inventory",
  },
  {
    id: "damaged",
    name: "Damaged Items",
    description: "Handling damaged inventory",
  },
  {
    id: "disposition",
    name: "Disposition Workflow",
    description: "Final disposition of items",
  },
];
