/**
 * Picking & Scanning Out Module Use Cases
 */

export const pickingUseCases = [
  // Standard Picking Use Cases
  {
    id: "pick-single-location",
    module: "picking",
    category: "standard",
    title: "Single Location Pick",
    complexity: "basic",
    description: "Pick item from single warehouse location",
    testSteps: [
      "Receive pick list for order",
      "Navigate to bin location",
      "Scan location barcode",
      "Scan product GS1 barcode",
      "Verify lot and expiry",
      "Confirm quantity picked",
      "Move to packing",
    ],
    expectedOutcome:
      "Item picked correctly, inventory decremented from location",
    productsNeeded: 1,
  },
  {
    id: "pick-multi-location",
    module: "picking",
    category: "standard",
    title: "Multi-Location Pick (Same Item)",
    complexity: "medium",
    description: "Pick same SKU from multiple locations to fulfill quantity",
    testSteps: [
      "Pick list shows item needed: 50 units",
      "Location A has 30 units",
      "Location B has 20 units",
      "Pick 30 from Location A, scan and confirm",
      "Pick 20 from Location B, scan and confirm",
      "Verify total quantity: 50",
      "Consolidate for packing",
    ],
    expectedOutcome: "Quantity consolidated from multiple locations",
    productsNeeded: 1,
  },
  {
    id: "pick-fefo",
    module: "picking",
    category: "standard",
    title: "FEFO Enforcement Validation",
    complexity: "medium",
    description: "System enforces First Expired First Out picking",
    testSteps: [
      "Multiple lots in stock with different expiries",
      "Lot A: Exp 2026-03 (first to expire)",
      "Lot B: Exp 2026-09",
      "System directs to pick Lot A first",
      "Attempt to scan Lot B - system warns",
      "Pick Lot A as directed",
      "Complete pick",
    ],
    expectedOutcome: "FEFO enforced, oldest expiry picked first",
    productsNeeded: 1,
    flags: ["fefo"],
  },
  {
    id: "pick-lot-specific",
    module: "picking",
    category: "standard",
    title: "Lot-Specific Customer Requirements",
    complexity: "complex",
    description: "Pick specific lot required by customer",
    testSteps: [
      "Order specifies Lot XYZ123 required",
      "Locate Lot XYZ123 in warehouse",
      "Pick only from specified lot",
      "Scan to verify correct lot",
      "If wrong lot scanned, reject",
      "Complete pick with correct lot",
    ],
    expectedOutcome: "Only customer-specified lot picked",
    productsNeeded: 1,
    flags: ["lot-specific"],
  },
  {
    id: "pick-partial-substitution",
    module: "picking",
    category: "standard",
    title: "Partial Pick with Substitution",
    complexity: "complex",
    description: "Handle out-of-stock with approved substitution",
    testSteps: [
      "Pick list shows Item A, qty 100",
      "Only 60 of Item A available",
      "Substitution approved: Item B for remainder",
      "Pick 60 of Item A",
      "Pick 40 of Item B",
      "Document substitution on order",
      "Complete pick",
    ],
    expectedOutcome: "Order fulfilled with approved substitution documented",
    productsNeeded: 2,
    flags: ["substitution"],
  },
  {
    id: "pick-cross-dock",
    module: "picking",
    category: "standard",
    title: "Cross-Dock Scenario",
    complexity: "complex",
    description: "Pick directly from receiving dock without putaway",
    testSteps: [
      "Inbound shipment arrives",
      "Order waiting for this product",
      "Cross-dock flagged",
      "Pick directly from receiving",
      "Scan inbound product",
      "Move directly to outbound staging",
      "Skip putaway to storage",
    ],
    expectedOutcome: "Product moved directly from receiving to shipping",
    productsNeeded: 1,
    flags: ["cross-dock"],
  },

  // Break Pack Picking Use Cases
  {
    id: "pick-eaches-open-stock",
    module: "picking",
    category: "break-pack",
    title: "Pick Eaches from Open Stock",
    complexity: "medium",
    description: "Pick individual units from already-opened case",
    testSteps: [
      "Navigate to open stock location",
      "Verify open case available",
      "Scan unit GTIN (not case)",
      "Pick required quantity",
      "Update open stock count",
      "Complete pick",
    ],
    expectedOutcome: "Units picked from open stock, remaining count updated",
    productsNeeded: 1,
    flags: ["break-pack"],
  },
  {
    id: "pick-break-sealed",
    module: "picking",
    category: "break-pack",
    title: "Break Sealed Case, Scan Unit GTIN",
    complexity: "medium",
    description: "Open new case to pick individual units",
    testSteps: [
      "No open stock available",
      "Retrieve sealed case",
      "Open case",
      "Scan unit GTIN (different from case)",
      "Pick required eaches",
      "Move remaining to open stock bin",
      "Update inventory at unit level",
    ],
    expectedOutcome: "Case broken, units picked, remainder tracked",
    productsNeeded: 1,
    flags: ["break-pack"],
  },
  {
    id: "pick-cases-plus-eaches",
    module: "picking",
    category: "break-pack",
    title: "Pick Full Cases + Eaches",
    complexity: "complex",
    description: "Order requires both full cases and individual units",
    testSteps: [
      "Order: 75 units, case pack = 24",
      "Pick 3 full cases (72 units), scan case GTIN",
      "Break 4th case",
      "Pick 3 eaches, scan unit GTIN",
      "Move 21 remaining to open stock",
      "Verify total: 75 units",
      "Complete pick",
    ],
    expectedOutcome: "Efficient pick using full cases plus eaches",
    productsNeeded: 1,
    flags: ["break-pack"],
  },
  {
    id: "pick-break-new-case-mid-pick",
    module: "picking",
    category: "break-pack",
    title: "Break New Case Mid-Pick",
    complexity: "complex",
    description: "Open stock depleted during pick, break new case",
    testSteps: [
      "Order: 20 eaches",
      "Open stock: 12 units",
      "Pick 12 from open stock",
      "Open stock now empty",
      "Retrieve and break new case",
      "Pick remaining 8 units",
      "Track new open stock (16 remaining)",
      "Complete pick",
    ],
    expectedOutcome: "Seamless transition from open stock to new case",
    productsNeeded: 1,
    flags: ["break-pack"],
  },
];

export const pickingCategories = [
  {
    id: "standard",
    name: "Standard Picking",
    description: "Regular picking workflows",
  },
  {
    id: "break-pack",
    name: "Break Pack Picking",
    description: "Picking units from cases",
  },
];
