/**
 * Post-Sales Support / RMA Module Use Cases
 */

export const rmaUseCases = [
  // RMA Request Use Cases
  {
    id: "rma-basic-request",
    module: "rma",
    category: "request",
    title: "Customer Requests Return - Issue RMA",
    complexity: "basic",
    description: "Basic RMA request and number generation",
    testSteps: [
      "Customer contacts support",
      "Locate original order",
      "Verify return eligibility",
      "Select return reason code",
      "Generate RMA number",
      "Provide return instructions",
      "Send RMA confirmation to customer",
    ],
    expectedOutcome: "RMA number issued with return instructions",
    productsNeeded: 1,
  },
  {
    id: "rma-reason-code",
    module: "rma",
    category: "request",
    title: "RMA with Reason Code",
    complexity: "medium",
    description: "Capture detailed reason for return",
    testSteps: [
      "Create RMA request",
      "Select primary reason: Wrong Item",
      "Add secondary reason: Customer ordered incorrectly",
      "Document notes",
      "Determine restocking fee applicability",
      "Generate RMA with reason coded",
    ],
    expectedOutcome: "RMA issued with proper reason categorization",
    productsNeeded: 1,
  },
  {
    id: "rma-approval-workflow",
    module: "rma",
    category: "request",
    title: "RMA Approval Workflow",
    complexity: "medium",
    description: "RMA requires manager approval before issuing",
    testSteps: [
      "Create RMA request",
      "Value exceeds auto-approval threshold",
      "Route to manager for approval",
      "Manager reviews details",
      "Manager approves/denies",
      "If approved, generate RMA",
      "Notify customer of decision",
    ],
    expectedOutcome: "RMA approved through proper authorization chain",
    productsNeeded: 1,
  },
  {
    id: "rma-partial-order",
    module: "rma",
    category: "request",
    title: "Partial Order RMA",
    complexity: "complex",
    description: "Customer returns only some items from order",
    testSteps: [
      "Original order: 5 different items",
      "Customer wants to return 2 items",
      "Create RMA for specific line items",
      "Other items remain with customer",
      "Generate RMA for partial return",
      "Track which items expected back",
    ],
    expectedOutcome: "RMA covers only specific items being returned",
    productsNeeded: 2,
  },
  {
    id: "rma-advance-exchange",
    module: "rma",
    category: "request",
    title: "RMA with Replacement Order (Advance Exchange)",
    complexity: "complex",
    description: "Ship replacement before receiving return",
    testSteps: [
      "Customer needs replacement urgently",
      "Create RMA for return",
      "Create replacement order immediately",
      "Ship replacement to customer",
      "Track return of original",
      "If not returned, charge for both",
      "Close RMA when original received",
    ],
    expectedOutcome: "Replacement shipped, original tracked for return",
    productsNeeded: 1,
  },
  {
    id: "rma-outside-window",
    module: "rma",
    category: "request",
    title: "RMA Outside Return Window",
    complexity: "complex",
    description: "Handle return request after policy window expired",
    testSteps: [
      "Customer requests return",
      "Check order date: 45 days ago",
      "Return window: 30 days",
      "Flag as exception request",
      "Escalate to supervisor",
      "Document exception reason",
      "Approve/deny with justification",
    ],
    expectedOutcome: "Exception handled with proper documentation",
    productsNeeded: 1,
  },

  // Customer-Reported Damage Use Cases
  {
    id: "rma-doa",
    module: "rma",
    category: "damage",
    title: "DOA (Dead on Arrival) - Immediate Replacement",
    complexity: "basic",
    description: "Product arrives defective, immediate replacement",
    testSteps: [
      "Customer reports item DOA",
      "Verify order and delivery",
      "No troubleshooting needed",
      "Issue immediate RMA",
      "Ship replacement same day",
      "Provide return label for DOA item",
      "Track manufacturer warranty claim",
    ],
    expectedOutcome: "DOA replaced immediately, defective returned for claim",
    productsNeeded: 1,
  },
  {
    id: "rma-transit-damage",
    module: "rma",
    category: "damage",
    title: "Damage in Transit - Carrier Claim",
    complexity: "medium",
    description: "Package damaged by carrier during shipping",
    testSteps: [
      "Customer reports shipping damage",
      "Request photos of package/damage",
      "Document carrier and tracking",
      "File carrier claim",
      "Issue RMA or replacement",
      "Track claim resolution",
      "Recover from carrier",
    ],
    expectedOutcome: "Customer made whole, carrier claim filed",
    productsNeeded: 1,
  },
  {
    id: "rma-photo-required",
    module: "rma",
    category: "damage",
    title: "Photo Documentation Required",
    complexity: "medium",
    description: "Require photo evidence before approving damage RMA",
    testSteps: [
      "Customer reports damage",
      "Request photos of damage",
      "Customer submits photos",
      "Review photos for validity",
      "Approve or deny based on evidence",
      "If approved, issue RMA",
      "Store photos with RMA record",
    ],
    expectedOutcome: "Damage verified with photo documentation",
    productsNeeded: 1,
  },
  {
    id: "rma-partial-damage",
    module: "rma",
    category: "damage",
    title: "Partial Damage - Keep Good Units",
    complexity: "complex",
    description: "Some items damaged, customer keeps undamaged items",
    testSteps: [
      "Order: 10 units",
      "Customer reports 3 damaged",
      "Verify damage on 3 units",
      "Customer keeps 7 good units",
      "Issue RMA for 3 damaged only",
      "Credit or replace 3 units",
      "Adjust invoice if needed",
    ],
    expectedOutcome: "Partial credit/replacement for damaged items only",
    productsNeeded: 1,
  },
  {
    id: "rma-concealed-damage",
    module: "rma",
    category: "damage",
    title: "Concealed Damage After Use",
    complexity: "complex",
    description: "Damage discovered after customer began using product",
    testSteps: [
      "Customer reports damage after use",
      "Determine if damage existed pre-delivery",
      "Request photos/evidence",
      "Evaluate warranty coverage",
      "Decide: return, partial credit, or deny",
      "Process according to decision",
      "Document for future reference",
    ],
    expectedOutcome: "Fair resolution based on damage origin",
    productsNeeded: 1,
  },
  {
    id: "rma-manufacturer-defect",
    module: "rma",
    category: "damage",
    title: "Manufacturer Defect - Batch Investigation",
    complexity: "complex",
    description: "Defect may indicate batch-wide quality issue",
    testSteps: [
      "Customer reports defect",
      "Record lot/batch number",
      "Check for other complaints on same lot",
      "Initiate quality investigation",
      "Quarantine remaining inventory if needed",
      "Work with manufacturer on recall",
      "Resolve customer issue",
    ],
    expectedOutcome: "Individual resolved, systemic issue investigated",
    productsNeeded: 1,
    flags: ["quality-issue"],
  },

  // Return Receipt & Processing Use Cases
  {
    id: "rma-receipt-restock",
    module: "rma",
    category: "receipt",
    title: "Simple Return - Restock to Inventory",
    complexity: "basic",
    description: "Returned item in good condition, restock immediately",
    testSteps: [
      "Receive return at warehouse",
      "Scan RMA barcode",
      "Scan product GS1 barcode",
      "Inspect: condition good",
      "Return to sellable inventory",
      "Update stock levels",
      "Close RMA",
    ],
    expectedOutcome: "Product restocked, inventory updated",
    productsNeeded: 1,
  },
  {
    id: "rma-receipt-lot-verify",
    module: "rma",
    category: "receipt",
    title: "Return with Lot Verification",
    complexity: "medium",
    description: "Verify returned lot matches original shipment",
    testSteps: [
      "Receive return",
      "Scan product GS1 barcode",
      "Extract lot number from scan",
      "Compare to original sales order lot",
      "If match: accept return",
      "If mismatch: investigate/reject",
      "Process accordingly",
    ],
    expectedOutcome: "Lot verified against original sale",
    productsNeeded: 1,
  },
  {
    id: "rma-receipt-quarantine",
    module: "rma",
    category: "receipt",
    title: "Return to Quarantine for Inspection",
    complexity: "medium",
    description: "Returned item requires QC before restocking",
    testSteps: [
      "Receive return",
      "Route to quarantine location",
      "Generate QC inspection task",
      "Inspector evaluates condition",
      "Pass: release to inventory",
      "Fail: disposition (scrap/repair)",
      "Update RMA status",
    ],
    expectedOutcome: "Return inspected before disposition decision",
    productsNeeded: 1,
  },
  {
    id: "rma-receipt-vendor-credit",
    module: "rma",
    category: "receipt",
    title: "Damaged Return - Vendor Credit",
    complexity: "complex",
    description: "Return damaged item for vendor credit",
    testSteps: [
      "Receive damaged return",
      "Document damage condition",
      "Initiate vendor RMA",
      "Ship to vendor or dispose",
      "Track vendor credit pending",
      "Receive vendor credit",
      "Apply to AP account",
    ],
    expectedOutcome: "Damaged item credited by vendor",
    productsNeeded: 1,
  },
  {
    id: "rma-receipt-expired-disposal",
    module: "rma",
    category: "receipt",
    title: "Expired Return - Disposal Workflow",
    complexity: "complex",
    description: "Returned product is expired, must be disposed",
    testSteps: [
      "Receive return",
      "Scan GS1 - system flags expired",
      "Cannot restock expired product",
      "Route to disposal process",
      "Document disposal",
      "Update inventory (scrap)",
      "Complete credit to customer",
    ],
    expectedOutcome: "Expired product disposed, customer credited",
    productsNeeded: 1,
  },
  {
    id: "rma-receipt-restocking-fee",
    module: "rma",
    category: "receipt",
    title: "Return with Restocking Fee",
    complexity: "complex",
    description: "Calculate and apply restocking fee on return",
    testSteps: [
      "Receive return",
      "Check reason code for restocking fee",
      "Original value: $100",
      "Restocking fee: 15% = $15",
      "Credit amount: $85",
      "Process credit minus fee",
      "Document fee applied",
    ],
    expectedOutcome: "Restocking fee deducted from credit",
    productsNeeded: 1,
  },
  {
    id: "rma-receipt-cross-reference",
    module: "rma",
    category: "receipt",
    title: "Cross-Reference Original Sales Order",
    complexity: "complex",
    description: "Link return to original order for full traceability",
    testSteps: [
      "Receive return",
      "Scan RMA to find linked order",
      "Verify product matches order line",
      "Check lot matches shipped lot",
      "Confirm within return window",
      "Process return with full linkage",
      "Complete audit trail",
    ],
    expectedOutcome: "Full traceability from return to original sale",
    productsNeeded: 1,
  },

  // Credit & Refund Use Cases
  {
    id: "rma-refund-full",
    module: "rma",
    category: "credit",
    title: "Full Refund to Original Payment",
    complexity: "basic",
    description: "Refund full amount to original payment method",
    testSteps: [
      "Return received and processed",
      "Original payment: Credit card",
      "Initiate refund to card",
      "Process refund transaction",
      "Send refund confirmation",
      "Close RMA",
    ],
    expectedOutcome: "Full refund processed to original payment method",
    productsNeeded: 1,
  },
  {
    id: "rma-store-credit",
    module: "rma",
    category: "credit",
    title: "Store Credit Instead of Refund",
    complexity: "medium",
    description: "Issue store credit rather than cash refund",
    testSteps: [
      "Return processed",
      "Customer prefers store credit",
      "Or: Policy requires store credit",
      "Generate store credit value",
      "Apply to customer account",
      "Notify customer of credit balance",
      "Credit available for future orders",
    ],
    expectedOutcome: "Store credit issued and applied to account",
    productsNeeded: 1,
  },
  {
    id: "rma-partial-refund",
    module: "rma",
    category: "credit",
    title: "Partial Refund (Restocking Fee)",
    complexity: "medium",
    description: "Refund minus restocking fee or deductions",
    testSteps: [
      "Return value: $200",
      "Restocking fee: $30",
      "Refund amount: $170",
      "Process partial refund",
      "Document deduction reason",
      "Send itemized credit memo",
      "Close RMA",
    ],
    expectedOutcome: "Partial refund with deductions documented",
    productsNeeded: 1,
  },
  {
    id: "rma-refund-shipping",
    module: "rma",
    category: "credit",
    title: "Refund with Shipping Cost Recovery",
    complexity: "complex",
    description: "Include or exclude original shipping in refund",
    testSteps: [
      "Product value: $100",
      "Original shipping: $15",
      "If our error: refund $115",
      "If customer choice: refund $100",
      "Calculate appropriate refund",
      "Process refund",
      "Document shipping decision",
    ],
    expectedOutcome: "Correct refund amount including/excluding shipping",
    productsNeeded: 1,
  },
  {
    id: "rma-multi-line-credit",
    module: "rma",
    category: "credit",
    title: "Multi-Line Order Partial Credit",
    complexity: "complex",
    description: "Credit specific line items from multi-line order",
    testSteps: [
      "Original order: 5 items, $500 total",
      "Customer returns 2 items worth $150",
      "Create credit for $150",
      "Link to specific line items",
      "Original order shows partial credit",
      "Customer owes remaining $350",
      "Or: Refund $150 if already paid",
    ],
    expectedOutcome: "Precise credit for returned line items only",
    productsNeeded: 2,
  },
];

export const rmaCategories = [
  {
    id: "request",
    name: "RMA Requests",
    description: "Initiating return authorizations",
  },
  {
    id: "damage",
    name: "Customer-Reported Damage",
    description: "Handling damage claims",
  },
  {
    id: "receipt",
    name: "Return Receipt",
    description: "Receiving and processing returns",
  },
  {
    id: "credit",
    name: "Credit & Refund",
    description: "Issuing credits and refunds",
  },
];
