/**
 * Sales Order & Fulfillment Module Use Cases
 */

export const salesUseCases = [
  // Standard Sales Use Cases
  {
    id: "sales-single-line",
    module: "sales",
    category: "standard",
    title: "Single-Line Order, Full Stock",
    complexity: "basic",
    description: "Simple order with one product, full stock available",
    testSteps: [
      "Create Sales Order for single item",
      "Verify stock availability",
      "Confirm order",
      "Generate delivery note",
      "Pick and pack",
      "Complete delivery",
    ],
    expectedOutcome: "Order fulfilled completely, inventory decremented",
    productsNeeded: 1,
  },
  {
    id: "sales-multi-line",
    module: "sales",
    category: "standard",
    title: "Multi-Line Order",
    complexity: "medium",
    description: "Order with multiple different products",
    testSteps: [
      "Create Sales Order with 5 line items",
      "Verify stock for all items",
      "Confirm order",
      "Generate consolidated pick list",
      "Pick all items",
      "Pack and ship",
    ],
    expectedOutcome: "All line items fulfilled in single shipment",
    productsNeeded: 5,
  },
  {
    id: "sales-partial-fulfillment",
    module: "sales",
    category: "standard",
    title: "Partial Fulfillment (Backorder)",
    complexity: "medium",
    description: "Order where some items are out of stock",
    testSteps: [
      "Create order for 100 units",
      "Only 60 units in stock",
      "Ship available 60 units",
      "Create backorder for 40 units",
      "When stock arrives, fulfill backorder",
    ],
    expectedOutcome:
      "Partial shipment sent, backorder tracked and fulfilled when stock available",
    productsNeeded: 1,
  },
  {
    id: "sales-lot-requirements",
    module: "sales",
    category: "standard",
    title: "Customer-Specific Lot Requirements",
    complexity: "complex",
    description:
      "Customer requires specific lot number or excludes certain lots",
    testSteps: [
      "Create order with lot restriction note",
      "System filters available lots",
      "Select only approved lot",
      "Generate pick list for specific lot",
      "Verify lot on scan",
      "Complete shipment",
    ],
    expectedOutcome: "Order fulfilled from customer-approved lot only",
    productsNeeded: 1,
    flags: ["lot-specific"],
  },
  {
    id: "sales-expiry-restriction",
    module: "sales",
    category: "standard",
    title: "Expiry Date Restrictions (Min Shelf Life)",
    complexity: "complex",
    description: "Customer requires minimum remaining shelf life on products",
    testSteps: [
      "Customer requires 6+ months shelf life",
      "Create order with shelf life restriction",
      "System excludes short-dated lots",
      "Pick from compliant lots only",
      "Verify expiry on scan",
      "Complete order",
    ],
    expectedOutcome:
      "Order fulfilled only with products meeting shelf life requirement",
    productsNeeded: 1,
    flags: ["expiry-restriction"],
  },
  {
    id: "sales-split-shipment",
    module: "sales",
    category: "standard",
    title: "Split Shipment Across Warehouses",
    complexity: "complex",
    description: "Order fulfilled from multiple warehouse locations",
    testSteps: [
      "Create order for 100 units",
      "Warehouse A has 60 units",
      "Warehouse B has 40 units",
      "Generate split pick lists",
      "Ship from both locations",
      "Track consolidated delivery",
    ],
    expectedOutcome:
      "Order fulfilled via multiple shipments from different warehouses",
    productsNeeded: 1,
    flags: ["multi-warehouse"],
  },

  // Break Pack Use Cases
  {
    id: "sales-break-pack-basic",
    module: "sales",
    category: "break-pack",
    title: "Sell Eaches When Only Cases in Stock",
    complexity: "medium",
    description:
      "Customer orders individual units but only full cases are available",
    testSteps: [
      "Order received for 5 eaches",
      "Only full cases (24 units each) in stock",
      "Break open one case",
      "Pick 5 eaches from broken case",
      "Move remaining 19 to open stock location",
      "Complete order",
    ],
    expectedOutcome:
      "Order fulfilled, remaining units tracked in open stock location",
    productsNeeded: 1,
    flags: ["break-pack"],
  },
  {
    id: "sales-break-pack-remaining",
    module: "sales",
    category: "break-pack",
    title: "Break Pack with Open Stock Tracking",
    complexity: "medium",
    description: "Track remaining units after breaking a case",
    testSteps: [
      "Break case of 24 units",
      "Sell 10 units",
      "Remaining 14 to open stock bin",
      "Scan case barcode",
      "System tracks partial case inventory",
      "Next order pulls from open stock first",
    ],
    expectedOutcome:
      "Open stock properly tracked, FIFO from open stock on future orders",
    productsNeeded: 1,
    flags: ["break-pack"],
  },
  {
    id: "sales-break-pack-mixed",
    module: "sales",
    category: "break-pack",
    title: "Mixed Order - Full Cases + Eaches",
    complexity: "complex",
    description:
      "Order contains both full case quantities and individual units",
    testSteps: [
      "Order for 50 units (case pack = 24)",
      "Pick 2 full cases (48 units)",
      "Break third case for 2 eaches",
      "Move remaining 22 to open stock",
      "Scan and verify all items",
      "Complete shipment",
    ],
    expectedOutcome: "Efficient fulfillment using full cases plus eaches",
    productsNeeded: 1,
    flags: ["break-pack"],
  },
  {
    id: "sales-break-pack-lot-tracking",
    module: "sales",
    category: "break-pack",
    title: "Break Pack with Lot/Expiry Tracking",
    complexity: "complex",
    description: "Maintain lot and expiry tracking when breaking cases",
    testSteps: [
      "Break case from Lot A, Exp 2026-06",
      "Pick eaches from broken case",
      "System maintains lot/expiry on eaches",
      "Scan unit GTIN (different from case)",
      "Verify lot transfers to unit level",
      "Complete order with traced units",
    ],
    expectedOutcome: "Full lot/expiry traceability maintained at each level",
    productsNeeded: 1,
    flags: ["break-pack", "lot-tracking"],
  },
  {
    id: "sales-break-pack-open-first",
    module: "sales",
    category: "break-pack",
    title: "Pick from Open Stock First",
    complexity: "complex",
    description:
      "System prioritizes already-open cases before breaking new ones",
    testSteps: [
      "Open stock has 15 eaches available",
      "Order for 20 eaches received",
      "Pick 15 from open stock first",
      "Break new case for remaining 5",
      "Verify FIFO/FEFO across open and sealed stock",
      "Complete order",
    ],
    expectedOutcome: "Open stock depleted before breaking new cases",
    productsNeeded: 1,
    flags: ["break-pack"],
  },
];

export const salesCategories = [
  {
    id: "standard",
    name: "Standard Orders",
    description: "Regular sales order workflows",
  },
  {
    id: "break-pack",
    name: "Break Pack / Each Pick",
    description: "Selling units from cases",
  },
];
